// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package testmodel

import (
	"fmt"
	"slices"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// SubtaskIdentity represents the Identity of the object.
var SubtaskIdentity = elemental.Identity{
	Name:     "subtask",
	Category: "subtasks",
	Package:  "todo-list",
	Private:  false,
}

// SubtasksList represents a list of Subtasks
type SubtasksList []*Subtask

// Identity returns the identity of the objects in the list.
func (o SubtasksList) Identity() elemental.Identity {

	return SubtaskIdentity
}

// Copy returns a pointer to a copy the SubtasksList.
func (o SubtasksList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the SubtasksList.
func (o SubtasksList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*Subtask))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SubtasksList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SubtasksList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the SubtasksList converted to SparseSubtasksList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o SubtasksList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseSubtasksList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseSubtask)
	}

	return out
}

// Version returns the version of the content.
func (o SubtasksList) Version() int {

	return 1
}

// Subtask represents the model of a subtask
type Subtask struct {
	// The identifier.
	ID string `json:"ID" msgpack:"ID" bson:"-" mapstructure:"ID,omitempty"`

	// The Name.
	Name string `json:"Name" msgpack:"Name" bson:"name" mapstructure:"Name,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// The identifier of the parent of the object.
	ParentID string `json:"parentID" msgpack:"parentID" bson:"parentid" mapstructure:"parentID,omitempty"`

	// The type of the parent of the object.
	ParentType string `json:"parentType" msgpack:"parentType" bson:"parenttype" mapstructure:"parentType,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSubtask returns a new *Subtask
func NewSubtask() *Subtask {

	return &Subtask{
		ModelVersion: 1,
	}
}

// Identity returns the Identity of the object.
func (o *Subtask) Identity() elemental.Identity {

	return SubtaskIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *Subtask) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *Subtask) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *Subtask) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSubtask{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.Name = o.Name
	s.Namespace = o.Namespace
	s.ParentID = o.ParentID
	s.ParentType = o.ParentType

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *Subtask) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesSubtask{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.Name = s.Name
	o.Namespace = s.Namespace
	o.ParentID = s.ParentID
	o.ParentType = s.ParentType

	return nil
}

// Version returns the hardcoded version of the model.
func (o *Subtask) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *Subtask) BleveType() string {

	return "subtask"
}

// DefaultOrder returns the list of default ordering fields.
func (o *Subtask) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *Subtask) Doc() string {

	return `Represent a subtask object.`
}

func (o *Subtask) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetNamespace returns the Namespace of the receiver.
func (o *Subtask) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *Subtask) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *Subtask) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseSubtask{
			ID:         &o.ID,
			Name:       &o.Name,
			Namespace:  &o.Namespace,
			ParentID:   &o.ParentID,
			ParentType: &o.ParentType,
		}
	}

	sp := &SparseSubtask{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "Name":
			sp.Name = &(o.Name)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "parentID":
			sp.ParentID = &(o.ParentID)
		case "parentType":
			sp.ParentType = &(o.ParentType)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseSubtask to the object.
func (o *Subtask) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseSubtask)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.Name != nil {
		o.Name = *so.Name
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.ParentID != nil {
		o.ParentID = *so.ParentID
	}
	if so.ParentType != nil {
		o.ParentType = *so.ParentType
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *Subtask) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *Subtask) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the Subtask.
func (o *Subtask) DeepCopy() *Subtask {

	if o == nil {
		return nil
	}

	out := &Subtask{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *Subtask.
func (o *Subtask) DeepCopyInto(out *Subtask) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy Subtask: %s", err))
	}

	*out = *target.(*Subtask)
}

// Validate valides the current information stored into the structure.
func (o *Subtask) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*Subtask) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := SubtaskAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return SubtaskLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*Subtask) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return SubtaskAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *Subtask) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "Name":
		return o.Name
	case "namespace":
		return o.Namespace
	case "parentID":
		return o.ParentID
	case "parentType":
		return o.ParentType
	}

	return nil
}

// SubtaskAttributesMap represents the map of attribute for Subtask.
var SubtaskAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `The identifier.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		PrimaryKey:     true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"Name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The Name.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "Name",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"ParentID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "parentid",
		ConvertedName:  "ParentID",
		Description:    `The identifier of the parent of the object.`,
		Exposed:        true,
		Filterable:     true,
		ForeignKey:     true,
		Name:           "parentID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"ParentType": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "parenttype",
		ConvertedName:  "ParentType",
		Description:    `The type of the parent of the object.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "parentType",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
}

// SubtaskLowerCaseAttributesMap represents the map of attribute for Subtask.
var SubtaskLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `The identifier.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		PrimaryKey:     true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The Name.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "Name",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"parentid": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "parentid",
		ConvertedName:  "ParentID",
		Description:    `The identifier of the parent of the object.`,
		Exposed:        true,
		Filterable:     true,
		ForeignKey:     true,
		Name:           "parentID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"parenttype": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "parenttype",
		ConvertedName:  "ParentType",
		Description:    `The type of the parent of the object.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "parentType",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
}

// SparseSubtasksList represents a list of SparseSubtasks
type SparseSubtasksList []*SparseSubtask

// Identity returns the identity of the objects in the list.
func (o SparseSubtasksList) Identity() elemental.Identity {

	return SubtaskIdentity
}

// Copy returns a pointer to a copy the SparseSubtasksList.
func (o SparseSubtasksList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseSubtasksList.
func (o SparseSubtasksList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseSubtask))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseSubtasksList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseSubtasksList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseSubtasksList converted to SubtasksList.
func (o SparseSubtasksList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseSubtasksList) Version() int {

	return 1
}

// SparseSubtask represents the sparse version of a subtask.
type SparseSubtask struct {
	// The identifier.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// The Name.
	Name *string `json:"Name,omitempty" msgpack:"Name,omitempty" bson:"name,omitempty" mapstructure:"Name,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// The identifier of the parent of the object.
	ParentID *string `json:"parentID,omitempty" msgpack:"parentID,omitempty" bson:"parentid,omitempty" mapstructure:"parentID,omitempty"`

	// The type of the parent of the object.
	ParentType *string `json:"parentType,omitempty" msgpack:"parentType,omitempty" bson:"parenttype,omitempty" mapstructure:"parentType,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseSubtask returns a new  SparseSubtask.
func NewSparseSubtask() *SparseSubtask {
	return &SparseSubtask{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseSubtask) Identity() elemental.Identity {

	return SubtaskIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseSubtask) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseSubtask) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseSubtask) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseSubtask{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.Name != nil {
		s.Name = o.Name
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.ParentID != nil {
		s.ParentID = o.ParentID
	}
	if o.ParentType != nil {
		s.ParentType = o.ParentType
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseSubtask) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseSubtask{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.Name != nil {
		o.Name = s.Name
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.ParentID != nil {
		o.ParentID = s.ParentID
	}
	if s.ParentType != nil {
		o.ParentType = s.ParentType
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseSubtask) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseSubtask) ToPlain() elemental.PlainIdentifiable {

	out := NewSubtask()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.Name != nil {
		out.Name = *o.Name
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.ParentID != nil {
		out.ParentID = *o.ParentID
	}
	if o.ParentType != nil {
		out.ParentType = *o.ParentType
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparseSubtask) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparseSubtask) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseSubtask) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseSubtask) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// DeepCopy returns a deep copy if the SparseSubtask.
func (o *SparseSubtask) DeepCopy() *SparseSubtask {

	if o == nil {
		return nil
	}

	out := &SparseSubtask{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseSubtask.
func (o *SparseSubtask) DeepCopyInto(out *SparseSubtask) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseSubtask: %s", err))
	}

	*out = *target.(*SparseSubtask)
}

type mongoAttributesSubtask struct {
	ID         bson.ObjectId `bson:"_id,omitempty"`
	Name       string        `bson:"name"`
	Namespace  string        `bson:"namespace,omitempty"`
	ParentID   string        `bson:"parentid"`
	ParentType string        `bson:"parenttype"`
}
type mongoAttributesSparseSubtask struct {
	ID         bson.ObjectId `bson:"_id,omitempty"`
	Name       *string       `bson:"name,omitempty"`
	Namespace  *string       `bson:"namespace,omitempty"`
	ParentID   *string       `bson:"parentid,omitempty"`
	ParentType *string       `bson:"parenttype,omitempty"`
}
